# Generated by Django 5.1.4 on 2025-01-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_section_section_image_subsection_sub_section_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='sub_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
